# Generated by Django 4.2.7 on 2025-12-06 12:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='农产品名称')),
                ('region', models.CharField(max_length=50, verbose_name='地区')),
                ('advice_type', models.CharField(choices=[('purchase', '采购建议'), ('sale', '销售建议'), ('storage', '仓储建议'), ('transport', '运输建议')], max_length=50, verbose_name='建议类型')),
                ('advice_content', models.TextField(verbose_name='建议内容')),
                ('confidence', models.FloatField(default=0.0, verbose_name='置信度')),
                ('factors', models.JSONField(default=list, verbose_name='影响因素')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '决策建议',
                'verbose_name_plural': '决策建议',
                'db_table': 'decision_advice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfitSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='农产品名称')),
                ('region', models.CharField(max_length=50, verbose_name='地区')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='采购价格')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='销售价格')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='数量')),
                ('unit', models.CharField(default='斤', max_length=20, verbose_name='单位')),
                ('transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='运输成本')),
                ('storage_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='仓储成本')),
                ('other_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='其他成本')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='总成本')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='总收入')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='利润')),
                ('profit_rate', models.FloatField(verbose_name='利润率(%)')),
                ('simulation_date', models.DateField(verbose_name='模拟日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '利润模拟',
                'verbose_name_plural': '利润模拟',
                'db_table': 'profit_simulation',
                'ordering': ['-simulation_date', '-created_at'],
            },
        ),
    ]
