# Generated by Django 4.2.7 on 2025-12-06 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='数据源名称')),
                ('url', models.URLField(verbose_name='数据源URL')),
                ('source_type', models.CharField(choices=[('web', '网页爬虫'), ('api', 'API接口'), ('file', '文件导入')], default='web', max_length=50, verbose_name='数据源类型')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '禁用')], default='active', max_length=20, verbose_name='状态')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据源',
                'verbose_name_plural': '数据源',
                'db_table': 'data_source',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='农产品名称')),
                ('product_category', models.CharField(max_length=50, verbose_name='农产品类别')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('unit', models.CharField(default='元/斤', max_length=20, verbose_name='单位')),
                ('market_name', models.CharField(max_length=100, verbose_name='市场名称')),
                ('region', models.CharField(max_length=50, verbose_name='地区')),
                ('date', models.DateField(verbose_name='日期')),
                ('raw_content', models.TextField(blank=True, verbose_name='原始内容')),
                ('status', models.CharField(choices=[('pending', '待清洗'), ('cleaned', '已清洗'), ('error', '清洗失败')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_etl.datasource', verbose_name='数据源')),
            ],
            options={
                'verbose_name': '原始数据',
                'verbose_name_plural': '原始数据',
                'db_table': 'raw_data',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ETLTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('failed', '失败')], default='running', max_length=20, verbose_name='状态')),
                ('total_count', models.IntegerField(default=0, verbose_name='总记录数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_etl.datasource', verbose_name='数据源')),
            ],
            options={
                'verbose_name': 'ETL任务',
                'verbose_name_plural': 'ETL任务',
                'db_table': 'etl_task',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CleanedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='农产品名称')),
                ('product_category', models.CharField(max_length=50, verbose_name='农产品类别')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('unit', models.CharField(default='元/斤', max_length=20, verbose_name='单位')),
                ('market_name', models.CharField(max_length=100, verbose_name='市场名称')),
                ('region', models.CharField(max_length=50, verbose_name='地区')),
                ('date', models.DateField(verbose_name='日期')),
                ('quality_score', models.FloatField(default=1.0, verbose_name='数据质量评分')),
                ('cleaned_at', models.DateTimeField(auto_now_add=True, verbose_name='清洗时间')),
                ('raw_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data_etl.rawdata', verbose_name='原始数据')),
            ],
            options={
                'verbose_name': '清洗数据',
                'verbose_name_plural': '清洗数据',
                'db_table': 'cleaned_data',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='rawdata',
            index=models.Index(fields=['product_name', 'date'], name='raw_data_product_cd4074_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdata',
            index=models.Index(fields=['region', 'date'], name='raw_data_region_8527ad_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaneddata',
            index=models.Index(fields=['product_name', 'date'], name='cleaned_dat_product_151e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaneddata',
            index=models.Index(fields=['region', 'date'], name='cleaned_dat_region_fd7dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaneddata',
            index=models.Index(fields=['date'], name='cleaned_dat_date_530831_idx'),
        ),
    ]
