# Generated by Django 4.2.7 on 2025-12-06 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='农产品名称')),
                ('product_category', models.CharField(max_length=50, verbose_name='农产品类别')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='需求数量')),
                ('unit', models.CharField(default='斤', max_length=20, verbose_name='单位')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最高价格')),
                ('region', models.CharField(max_length=50, verbose_name='地区')),
                ('contact_name', models.CharField(max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('active', '有效'), ('completed', '已完成'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '需求信息',
                'verbose_name_plural': '需求信息',
                'db_table': 'demand_info',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='农产品名称')),
                ('product_category', models.CharField(max_length=50, verbose_name='农产品类别')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='供应数量')),
                ('unit', models.CharField(default='斤', max_length=20, verbose_name='单位')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('region', models.CharField(max_length=50, verbose_name='地区')),
                ('contact_name', models.CharField(max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('active', '有效'), ('completed', '已完成'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '供应信息',
                'verbose_name_plural': '供应信息',
                'db_table': 'supply_info',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(verbose_name='匹配度')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='匹配时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.demandinfo', verbose_name='需求信息')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.supplyinfo', verbose_name='供应信息')),
            ],
            options={
                'verbose_name': '交易匹配',
                'verbose_name_plural': '交易匹配',
                'db_table': 'trade_match',
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supplyinfo',
            index=models.Index(fields=['product_name', 'status'], name='supply_info_product_49940b_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyinfo',
            index=models.Index(fields=['region', 'status'], name='supply_info_region_dac42d_idx'),
        ),
        migrations.AddIndex(
            model_name='demandinfo',
            index=models.Index(fields=['product_name', 'status'], name='demand_info_product_bf193b_idx'),
        ),
        migrations.AddIndex(
            model_name='demandinfo',
            index=models.Index(fields=['region', 'status'], name='demand_info_region_09d695_idx'),
        ),
    ]
