# Generated by Django 4.2.7 on 2025-12-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='农产品名称')),
                ('product_category', models.CharField(max_length=50, verbose_name='农产品类别')),
                ('region', models.CharField(max_length=50, verbose_name='地区')),
                ('stat_date', models.DateField(verbose_name='统计日期')),
                ('stat_type', models.CharField(choices=[('daily', '日统计'), ('weekly', '周统计'), ('monthly', '月统计')], max_length=20, verbose_name='统计类型')),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='平均价格')),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最高价格')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低价格')),
                ('price_std', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='价格标准差')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='交易量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '市场统计',
                'verbose_name_plural': '市场统计',
                'db_table': 'market_statistics',
                'ordering': ['-stat_date', 'product_name'],
                'indexes': [models.Index(fields=['product_name', 'stat_date'], name='market_stat_product_f24272_idx'), models.Index(fields=['region', 'stat_date'], name='market_stat_region_2c9473_idx')],
                'unique_together': {('product_name', 'region', 'stat_date', 'stat_type')},
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='农产品名称')),
                ('product_category', models.CharField(max_length=50, verbose_name='农产品类别')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('unit', models.CharField(default='元/斤', max_length=20, verbose_name='单位')),
                ('market_name', models.CharField(max_length=100, verbose_name='市场名称')),
                ('region', models.CharField(max_length=50, verbose_name='地区')),
                ('date', models.DateField(verbose_name='日期')),
                ('price_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格变化')),
                ('price_change_rate', models.FloatField(blank=True, null=True, verbose_name='价格变化率(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '市场价格',
                'verbose_name_plural': '市场价格',
                'db_table': 'market_price',
                'ordering': ['-date', 'product_name'],
                'indexes': [models.Index(fields=['product_name', 'date'], name='market_pric_product_d30d02_idx'), models.Index(fields=['region', 'date'], name='market_pric_region_4ad8fe_idx'), models.Index(fields=['date'], name='market_pric_date_5bc2c1_idx')],
                'unique_together': {('product_name', 'market_name', 'date')},
            },
        ),
    ]
