# Generated by Django 4.2.7 on 2025-12-06 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True, verbose_name='模型名称')),
                ('model_type', models.CharField(choices=[('ARIMA', 'ARIMA模型'), ('LSTM', 'LSTM神经网络'), ('Linear', '线性回归')], max_length=50, verbose_name='模型类型')),
                ('product_name', models.CharField(max_length=100, verbose_name='农产品名称')),
                ('region', models.CharField(max_length=50, verbose_name='地区')),
                ('parameters', models.JSONField(default=dict, verbose_name='模型参数')),
                ('accuracy_metrics', models.JSONField(default=dict, verbose_name='准确度指标')),
                ('model_file_path', models.CharField(blank=True, max_length=255, verbose_name='模型文件路径')),
                ('status', models.CharField(choices=[('training', '训练中'), ('ready', '就绪'), ('failed', '训练失败')], default='training', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('trained_at', models.DateTimeField(blank=True, null=True, verbose_name='训练时间')),
            ],
            options={
                'verbose_name': '预测模型',
                'verbose_name_plural': '预测模型',
                'db_table': 'forecast_model',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_data_start', models.DateField(verbose_name='训练数据起始日期')),
                ('training_data_end', models.DateField(verbose_name='训练数据结束日期')),
                ('data_count', models.IntegerField(verbose_name='数据量')),
                ('training_duration', models.FloatField(null=True, verbose_name='训练时长(秒)')),
                ('accuracy_metrics', models.JSONField(default=dict, verbose_name='准确度指标')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='训练时间')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.forecastmodel', verbose_name='预测模型')),
            ],
            options={
                'verbose_name': '训练历史',
                'verbose_name_plural': '训练历史',
                'db_table': 'training_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='农产品名称')),
                ('region', models.CharField(max_length=50, verbose_name='地区')),
                ('forecast_date', models.DateField(verbose_name='预测日期')),
                ('forecast_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预测价格')),
                ('confidence_interval_lower', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='置信区间下限')),
                ('confidence_interval_upper', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='置信区间上限')),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际价格')),
                ('error', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预测误差')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.forecastmodel', verbose_name='预测模型')),
            ],
            options={
                'verbose_name': '预测结果',
                'verbose_name_plural': '预测结果',
                'db_table': 'forecast_result',
                'ordering': ['-forecast_date', 'product_name'],
                'indexes': [models.Index(fields=['product_name', 'forecast_date'], name='forecast_re_product_30b9d2_idx'), models.Index(fields=['region', 'forecast_date'], name='forecast_re_region_5c020f_idx')],
            },
        ),
    ]
