# Generated by Django 4.2.7 on 2025-12-06 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='农产品名称')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='地区')),
                ('alert_type', models.CharField(choices=[('price_rise', '价格上涨'), ('price_fall', '价格下跌'), ('price_abnormal', '价格异常')], max_length=50, verbose_name='预警类型')),
                ('threshold_type', models.CharField(choices=[('absolute', '绝对值'), ('percentage', '百分比')], max_length=50, verbose_name='阈值类型')),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='阈值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预警规则',
                'verbose_name_plural': '预警规则',
                'db_table': 'alert_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='农产品名称')),
                ('region', models.CharField(max_length=50, verbose_name='地区')),
                ('alert_type', models.CharField(choices=[('price_rise', '价格上涨'), ('price_fall', '价格下跌'), ('price_abnormal', '价格异常')], max_length=50, verbose_name='预警类型')),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='阈值')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当前价格')),
                ('change_rate', models.FloatField(verbose_name='变化率(%)')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processed', '已处理'), ('ignored', '已忽略')], default='pending', max_length=20, verbose_name='状态')),
                ('message', models.TextField(verbose_name='预警信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
            ],
            options={
                'verbose_name': '价格预警',
                'verbose_name_plural': '价格预警',
                'db_table': 'price_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('analyst', '分析师'), ('trader', '交易员'), ('viewer', '查看者')], default='viewer', max_length=50, verbose_name='角色')),
                ('permissions', models.JSONField(default=dict, verbose_name='权限配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户权限',
                'verbose_name_plural': '用户权限',
                'db_table': 'user_permission',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('message_type', models.CharField(choices=[('alert', '预警通知'), ('system', '系统通知'), ('trade', '交易通知'), ('other', '其他')], default='system', max_length=50, verbose_name='消息类型')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('related_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='admincore.pricealert', verbose_name='关联预警')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '站内信',
                'verbose_name_plural': '站内信',
                'db_table': 'user_message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='农产品名称')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='地区')),
                ('alert_type', models.CharField(choices=[('price_rise', '价格上涨'), ('price_fall', '价格下跌'), ('price_abnormal', '价格异常')], max_length=50, verbose_name='预警类型')),
                ('threshold_type', models.CharField(choices=[('absolute', '绝对值'), ('percentage', '百分比')], max_length=50, verbose_name='阈值类型')),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='阈值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户预警订阅',
                'verbose_name_plural': '用户预警订阅',
                'db_table': 'user_alert_subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('debug', '调试')], max_length=50, verbose_name='日志类型')),
                ('module', models.CharField(max_length=100, verbose_name='模块')),
                ('action', models.CharField(max_length=100, verbose_name='操作')),
                ('message', models.TextField(verbose_name='日志内容')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'db_table': 'system_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('announcement_type', models.CharField(choices=[('system', '系统公告'), ('maintenance', '维护公告'), ('update', '更新公告'), ('other', '其他')], default='system', max_length=50, verbose_name='公告类型')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=20, verbose_name='优先级')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '系统公告',
                'verbose_name_plural': '系统公告',
                'db_table': 'system_announcement',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['product_name', 'status'], name='price_alert_product_30ce69_idx'),
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['alert_type', 'status'], name='price_alert_alert_t_da4a92_idx'),
        ),
        migrations.AddIndex(
            model_name='usermessage',
            index=models.Index(fields=['user', 'is_read'], name='user_messag_user_id_c5daf5_idx'),
        ),
        migrations.AddIndex(
            model_name='usermessage',
            index=models.Index(fields=['message_type', 'created_at'], name='user_messag_message_256660_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useralertsubscription',
            unique_together={('user', 'product_name', 'region', 'alert_type')},
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['log_type', 'created_at'], name='system_log_log_typ_3a8013_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['module', 'created_at'], name='system_log_module_afa049_idx'),
        ),
        migrations.AddIndex(
            model_name='systemannouncement',
            index=models.Index(fields=['is_published', 'publish_at'], name='system_anno_is_publ_b78376_idx'),
        ),
        migrations.AddIndex(
            model_name='systemannouncement',
            index=models.Index(fields=['announcement_type', 'is_published'], name='system_anno_announc_02b0eb_idx'),
        ),
    ]
